// Generated by scripts/build-field-assets.mjs. Do not edit by hand.
export const FIELD_ASSET_VERSION = 8 as const;
export const FIELD_OBJECT_ATLAS = {
  "width": 2048,
  "height": 2176,
  "assets": {
    "jungleSW": {
      "x": 8,
      "y": 8,
      "width": 330,
      "height": 330
    },
    "jungleNE": {
      "x": 346,
      "y": 8,
      "width": 329,
      "height": 330
    },
    "jungleNW": {
      "x": 683,
      "y": 8,
      "width": 329,
      "height": 330
    },
    "jungleSE": {
      "x": 1020,
      "y": 8,
      "width": 328,
      "height": 330
    },
    "map2Center": {
      "x": 8,
      "y": 346,
      "width": 1093,
      "height": 328
    },
    "parkCornerSE": {
      "x": 1109,
      "y": 346,
      "width": 329,
      "height": 275
    },
    "parkCornerSW": {
      "x": 1446,
      "y": 346,
      "width": 322,
      "height": 275
    },
    "parkCornerNE": {
      "x": 8,
      "y": 682,
      "width": 330,
      "height": 273
    },
    "parkCornerNW": {
      "x": 346,
      "y": 682,
      "width": 330,
      "height": 273
    },
    "parkPrisonRedFloor": {
      "x": 684,
      "y": 682,
      "width": 279,
      "height": 250
    },
    "parkPrisonRedOverlay": {
      "x": 971,
      "y": 682,
      "width": 279,
      "height": 250
    },
    "industrialPrisonBlueFloor": {
      "x": 1258,
      "y": 682,
      "width": 273,
      "height": 250
    },
    "industrialPrisonBlueOverlay": {
      "x": 1539,
      "y": 682,
      "width": 273,
      "height": 250
    },
    "parkPrisonBlueFloor": {
      "x": 8,
      "y": 963,
      "width": 264,
      "height": 250
    },
    "parkPrisonBlueOverlay": {
      "x": 280,
      "y": 963,
      "width": 264,
      "height": 250
    },
    "industrialPrisonRedFloor": {
      "x": 552,
      "y": 963,
      "width": 255,
      "height": 250
    },
    "industrialPrisonRedOverlay": {
      "x": 815,
      "y": 963,
      "width": 255,
      "height": 250
    },
    "canalStraightV": {
      "x": 1078,
      "y": 963,
      "width": 127,
      "height": 240
    },
    "canalBridgeV": {
      "x": 1213,
      "y": 963,
      "width": 133,
      "height": 220
    },
    "canalBarrierV": {
      "x": 1354,
      "y": 963,
      "width": 88,
      "height": 208
    },
    "coffeeStall": {
      "x": 1450,
      "y": 963,
      "width": 207,
      "height": 206
    },
    "map2PrisonGreenFloor": {
      "x": 1665,
      "y": 963,
      "width": 298,
      "height": 203
    },
    "map2PrisonGreenOverlay": {
      "x": 8,
      "y": 1221,
      "width": 298,
      "height": 203
    },
    "guardPost": {
      "x": 314,
      "y": 1221,
      "width": 222,
      "height": 202
    },
    "canalT": {
      "x": 544,
      "y": 1221,
      "width": 250,
      "height": 200
    },
    "canalBridgeDiag": {
      "x": 802,
      "y": 1221,
      "width": 195,
      "height": 200
    },
    "map2PrisonRedFloor": {
      "x": 1005,
      "y": 1221,
      "width": 291,
      "height": 199
    },
    "map2PrisonRedOverlay": {
      "x": 1304,
      "y": 1221,
      "width": 291,
      "height": 199
    },
    "hall": {
      "x": 1603,
      "y": 1221,
      "width": 222,
      "height": 198
    },
    "warung": {
      "x": 8,
      "y": 1432,
      "width": 209,
      "height": 198
    },
    "canalBarrierCorner": {
      "x": 225,
      "y": 1432,
      "width": 230,
      "height": 190
    },
    "canalCurve": {
      "x": 463,
      "y": 1432,
      "width": 165,
      "height": 190
    },
    "fortGreen": {
      "x": 636,
      "y": 1432,
      "width": 167,
      "height": 188
    },
    "fortRed": {
      "x": 811,
      "y": 1432,
      "width": 167,
      "height": 188
    },
    "tree": {
      "x": 986,
      "y": 1432,
      "width": 139,
      "height": 184
    },
    "parkTree": {
      "x": 1133,
      "y": 1432,
      "width": 130,
      "height": 184
    },
    "snackCart": {
      "x": 1271,
      "y": 1432,
      "width": 148,
      "height": 178
    },
    "clothesline": {
      "x": 1427,
      "y": 1432,
      "width": 206,
      "height": 170
    },
    "foodCart": {
      "x": 1641,
      "y": 1432,
      "width": 166,
      "height": 163
    },
    "marketStallB": {
      "x": 1815,
      "y": 1432,
      "width": 172,
      "height": 160
    },
    "marketStallC": {
      "x": 8,
      "y": 1638,
      "width": 165,
      "height": 160
    },
    "marketStallA": {
      "x": 181,
      "y": 1638,
      "width": 163,
      "height": 160
    },
    "prisonOverlay": {
      "x": 352,
      "y": 1638,
      "width": 254,
      "height": 157
    },
    "lamp": {
      "x": 614,
      "y": 1638,
      "width": 57,
      "height": 152
    },
    "parkLamp": {
      "x": 679,
      "y": 1638,
      "width": 68,
      "height": 150
    },
    "gardenMedium": {
      "x": 755,
      "y": 1638,
      "width": 190,
      "height": 148
    },
    "prisonFloor": {
      "x": 953,
      "y": 1638,
      "width": 254,
      "height": 142
    },
    "parkPlanter": {
      "x": 1215,
      "y": 1638,
      "width": 250,
      "height": 135
    },
    "parkFlowerFence": {
      "x": 1473,
      "y": 1638,
      "width": 270,
      "height": 130
    },
    "canalBridgeH": {
      "x": 1751,
      "y": 1638,
      "width": 220,
      "height": 128
    },
    "canalStraightH": {
      "x": 8,
      "y": 1806,
      "width": 280,
      "height": 122
    },
    "bush": {
      "x": 296,
      "y": 1806,
      "width": 144,
      "height": 118
    },
    "bunting": {
      "x": 448,
      "y": 1806,
      "width": 198,
      "height": 116
    },
    "canalBarrier": {
      "x": 654,
      "y": 1806,
      "width": 250,
      "height": 115
    },
    "crates": {
      "x": 912,
      "y": 1806,
      "width": 132,
      "height": 114
    },
    "canalBarrierLong": {
      "x": 1052,
      "y": 1806,
      "width": 340,
      "height": 113
    },
    "trash": {
      "x": 1400,
      "y": 1806,
      "width": 74,
      "height": 110
    },
    "flowerBedSmall": {
      "x": 1482,
      "y": 1806,
      "width": 126,
      "height": 104
    },
    "plant": {
      "x": 1616,
      "y": 1806,
      "width": 88,
      "height": 104
    },
    "parkBench": {
      "x": 1712,
      "y": 1806,
      "width": 220,
      "height": 100
    },
    "parkPlanterLong": {
      "x": 8,
      "y": 1936,
      "width": 340,
      "height": 99
    },
    "map2Cart": {
      "x": 356,
      "y": 1936,
      "width": 101,
      "height": 99
    },
    "bucket": {
      "x": 465,
      "y": 1936,
      "width": 112,
      "height": 97
    },
    "parkFlowerFenceLong": {
      "x": 585,
      "y": 1936,
      "width": 350,
      "height": 95
    },
    "map2PlanterRed": {
      "x": 943,
      "y": 1936,
      "width": 177,
      "height": 93
    },
    "drain": {
      "x": 1128,
      "y": 1936,
      "width": 233,
      "height": 88
    },
    "parkBarrier": {
      "x": 1369,
      "y": 1936,
      "width": 218,
      "height": 88
    },
    "parkBenchLong": {
      "x": 1595,
      "y": 1936,
      "width": 330,
      "height": 86
    },
    "map2PlanterGreen": {
      "x": 8,
      "y": 2043,
      "width": 168,
      "height": 83
    },
    "parkBarrierLong": {
      "x": 184,
      "y": 2043,
      "width": 330,
      "height": 74
    },
    "map2BarrierRed": {
      "x": 522,
      "y": 2043,
      "width": 172,
      "height": 69
    },
    "map2BarrierGreen": {
      "x": 702,
      "y": 2043,
      "width": 160,
      "height": 69
    },
    "map2Trash": {
      "x": 870,
      "y": 2043,
      "width": 47,
      "height": 65
    },
    "plantFence": {
      "x": 925,
      "y": 2043,
      "width": 244,
      "height": 47
    },
    "flowerFence": {
      "x": 1177,
      "y": 2043,
      "width": 244,
      "height": 40
    }
  }
} as const;
export const FIELD_ANIMATED_ATLAS = {
  "width": 1024,
  "height": 384,
  "animations": {
    "fountain": {
      "fps": 8,
      "width": 92,
      "height": 90,
      "frames": [
        {
          "x": 336,
          "y": 124,
          "width": 92,
          "height": 90
        },
        {
          "x": 436,
          "y": 124,
          "width": 92,
          "height": 90
        },
        {
          "x": 536,
          "y": 124,
          "width": 92,
          "height": 90
        },
        {
          "x": 636,
          "y": 124,
          "width": 92,
          "height": 90
        },
        {
          "x": 736,
          "y": 124,
          "width": 92,
          "height": 90
        },
        {
          "x": 836,
          "y": 124,
          "width": 92,
          "height": 90
        }
      ]
    },
    "flag": {
      "fps": 7,
      "width": 74,
      "height": 102,
      "frames": [
        {
          "x": 848,
          "y": 8,
          "width": 74,
          "height": 102
        },
        {
          "x": 930,
          "y": 8,
          "width": 74,
          "height": 102
        },
        {
          "x": 8,
          "y": 124,
          "width": 74,
          "height": 102
        },
        {
          "x": 90,
          "y": 124,
          "width": 74,
          "height": 102
        },
        {
          "x": 172,
          "y": 124,
          "width": 74,
          "height": 102
        },
        {
          "x": 254,
          "y": 124,
          "width": 74,
          "height": 102
        }
      ]
    },
    "vendor": {
      "fps": 5,
      "width": 132,
      "height": 108,
      "frames": [
        {
          "x": 8,
          "y": 8,
          "width": 132,
          "height": 108
        },
        {
          "x": 148,
          "y": 8,
          "width": 132,
          "height": 108
        },
        {
          "x": 288,
          "y": 8,
          "width": 132,
          "height": 108
        },
        {
          "x": 428,
          "y": 8,
          "width": 132,
          "height": 108
        },
        {
          "x": 568,
          "y": 8,
          "width": 132,
          "height": 108
        },
        {
          "x": 708,
          "y": 8,
          "width": 132,
          "height": 108
        }
      ]
    },
    "boost25": {
      "fps": 10,
      "width": 52,
      "height": 56,
      "frames": [
        {
          "x": 318,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 378,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 438,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 498,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 558,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 618,
          "y": 234,
          "width": 52,
          "height": 56
        }
      ]
    },
    "boost40": {
      "fps": 10,
      "width": 52,
      "height": 56,
      "frames": [
        {
          "x": 678,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 738,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 798,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 858,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 918,
          "y": 234,
          "width": 52,
          "height": 56
        },
        {
          "x": 8,
          "y": 300,
          "width": 52,
          "height": 56
        }
      ]
    },
    "boost75": {
      "fps": 10,
      "width": 52,
      "height": 56,
      "frames": [
        {
          "x": 68,
          "y": 300,
          "width": 52,
          "height": 56
        },
        {
          "x": 128,
          "y": 300,
          "width": 52,
          "height": 56
        },
        {
          "x": 188,
          "y": 300,
          "width": 52,
          "height": 56
        },
        {
          "x": 248,
          "y": 300,
          "width": 52,
          "height": 56
        },
        {
          "x": 308,
          "y": 300,
          "width": 52,
          "height": 56
        },
        {
          "x": 368,
          "y": 300,
          "width": 52,
          "height": 56
        }
      ]
    },
    "boost100": {
      "fps": 10,
      "width": 54,
      "height": 58,
      "frames": [
        {
          "x": 936,
          "y": 124,
          "width": 54,
          "height": 58
        },
        {
          "x": 8,
          "y": 234,
          "width": 54,
          "height": 58
        },
        {
          "x": 70,
          "y": 234,
          "width": 54,
          "height": 58
        },
        {
          "x": 132,
          "y": 234,
          "width": 54,
          "height": 58
        },
        {
          "x": 194,
          "y": 234,
          "width": 54,
          "height": 58
        },
        {
          "x": 256,
          "y": 234,
          "width": 54,
          "height": 58
        }
      ]
    }
  }
} as const;
export const FIELD_GROUND_ATLAS = {
  "width": 1280,
  "height": 448,
  "tiles": {
    "grass": {
      "x": 0,
      "y": 0,
      "width": 320,
      "height": 224
    },
    "dirt": {
      "x": 320,
      "y": 0,
      "width": 320,
      "height": 224
    },
    "paving": {
      "x": 640,
      "y": 0,
      "width": 320,
      "height": 224
    },
    "concrete": {
      "x": 960,
      "y": 0,
      "width": 320,
      "height": 224
    },
    "kampungGround": {
      "x": 0,
      "y": 224,
      "width": 320,
      "height": 224
    },
    "parkGrass": {
      "x": 320,
      "y": 224,
      "width": 320,
      "height": 224
    },
    "parkPaving": {
      "x": 640,
      "y": 224,
      "width": 320,
      "height": 224
    },
    "canalGrass": {
      "x": 960,
      "y": 224,
      "width": 320,
      "height": 224
    }
  }
} as const;
export type FieldAssetId = keyof typeof FIELD_OBJECT_ATLAS.assets;
export type FieldAnimatedId = keyof typeof FIELD_ANIMATED_ATLAS.animations;
export type GroundTileId = keyof typeof FIELD_GROUND_ATLAS.tiles;
